openapi: 3.1.0
info:
  version: 2.0.0
  title: Product recommendations
  description: Allows the retrieval of product recommendations.
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
x-readme-fauxas: true
x-samples-languages:
- curl
- csharp
- java
- javascript
- node
- python
- php
- ruby
externalDocs:
  description: Learn more about Dotdigital APIs
  url: https://developer.dotdigital.com
servers:
- url: https://{region}-api.dotdigital.com
  variables:
    region:
      default: r1
      enum:
      - r1
      - r2
      - r3
      description: The Dotdigital region id your account belongs to
security:
- basicAuth: []
paths:
  /v2/products/recommendations:
    parameters:
    - in: header
      name: x-ddg-integration-token
      required: false
      description: If you are a partner of Dotdigital and have a [verified integration](https://developer.dotdigital.com/docs/partner-integration-verification) then include your [integration tracking token](https://developer.dotdigital.co/docs/verified-integration-tracking) here.
      schema:
        type: string
        pattern: /^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$/
        example: 5a96bc79-19a7-4544-973b-e2da0c9136f9
    get:
      summary: Get all product recommendations
      deprecated: false
      description: Gets all product recommendations
      operationId: get-all-product-recommendations
      tags:
      - Programs
      parameters: []
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - dateLastRefreshed
                  - dateModified
                  - dateLastUsed
                  - name
                  - type
                  - status
                  - fallbackRecommendationId
                  - revenue
                  properties:
                    id:
                      description: The product recommendations unique ID.
                      type: integer
                      default: 0
                      examples:
                      - 1
                    dateLastRefreshed:
                      description: The date time the product recommendations were last refreshed in UTC ISO-8601 format.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01T09:40:18.527Z'
                    dateModified:
                      description: The date time the product recommendations were modified in UTC ISO-8601 format.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01T09:40:18.527Z'
                    dateLastUsed:
                      description: The date time the product recommendations were last used in UTC ISO-8601 format.
                      type: string
                      format: date-time
                      examples:
                      - '2020-01-01T09:40:18.527Z'
                    name:
                      description: The name of the product recommendation.
                      type: string
                      examples:
                      - Best sellers
                    type:
                      description: The type of product recommendation.
                      type: string
                      enum:
                      - BestSellers
                      - MostViewed
                      - FilterOnly
                      - LastBrowsed
                      - BoughtTogether
                      - Newest
                      - Lookalikes
                      - AlsoBought
                      - Trending
                      - BestNext
                      - NextOrderPrediction
                      - Hybrid
                      - ChurnPrediction
                      - CLVPrediction
                      - OrderCountPrediction
                      - RecentlyAdded
                      - AlsoBoughtV2
                      examples:
                      - BestSellers
                    status:
                      description: The status of the product recommendation.
                      type: string
                      enum:
                      - Ready
                      - InProgress
                      - Failed
                      - Queued
                      - Empty
                      - Warning
                      examples:
                      - Failed
                    fallbackRecommendationId:
                      description: The ID of the product recommendation to fall back to if the current one produces no recommendations.
                      type: integer
                      default: 0
                      examples:
                      - 12345
                    revenue:
                      description: The revenue value attributed with this product recommendation.
                      type: number
                      default: 0
                      examples:
                      - 199.99
              examples:
                Result:
                  summary: Accounts product recommendations
                  value:
                  - id: 1
                    dateLastRefreshed: '2020-01-01T09:40:18.527Z'
                    dateModified: '2020-01-01T09:40:18.527Z'
                    dateLastUsed: '2020-01-01T09:40:18.527Z'
                    name: Best sellers
                    type: BestSellers
                    status: Failed
                    fallbackRecommendationId: 0
                    revenue: 199.99
                  - id: 3021
                    dateLastRefreshed: '2020-01-01T09:40:18.527Z'
                    dateModified: '2020-01-01T09:40:18.527Z'
                    dateLastUsed: '2020-01-01T09:40:18.527Z'
                    name: Best sellers 2
                    type: BestSellers
                    status: Ready
                    fallbackRecommendationId: 12345
                    revenue: 0
                  - id: 6029
                    dateLastRefreshed: '2020-01-01T09:40:18.527Z'
                    dateModified: '2020-01-01T09:40:18.527Z'
                    dateLastUsed: '2020-01-01T09:40:18.527Z'
                    name: Also bought
                    type: AlsoBought
                    status: InProgress
                    fallbackRecommendationId: 0
                    revenue: 0
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
